### ISSUE TITLE
Unpaid invoices for 100.000 sats in my LN Wallet

### ISSUE THREAD

**Issue by thmsmullee** [nickfarrow/SatSale#35]
After installing SatSale yesterday I found 2 unpaid invoices for 100.000 sats in my Lightning Wallet.
How is it possible ?
Has it to do with the installation yesterday ?
Thanks

**Comment by nickfarrow** [comment]
Ahhhh pretty sure this is testing SatSale testing it can generate an invoice upon startup. I should probably test connection some other way or use a non-round number and a note somewhere.
https://github.com/nickfarrow/SatSale/blob/docker/node/lnd.py#L43
